Vagrant.configure("2") do |config|
  
  config.vm.define "kiamol" do |kiamol|
    kiamol.vm.box = "bento/ubuntu-20.04"  
    kiamol.vm.hostname = "kiamol"
    
    kiamol.vm.provision "shell", path: "./scripts/setup.sh"
    kiamol.vm.provision "shell", path: "./scripts/kiamol.sh", privileged: false

    kiamol.vm.synced_folder ".", "/kiamol", disabled: true
    

    kiamol.vm.provider :hyperv do |v|
      v.vmname = "kiamol"
      v.maxmemory = 4096
      v.cpus = 2
    end

    kiamol.vm.provider :virtualbox do |v|
      v.name = "kiamol"
      v.memory = 4096
      v.cpus = 2
    end
    
    # Konfiguracja NATSwitch
    kiamol.trigger.before :up do |trigger|
      trigger.info = "Creating 'NATSwitch' Hyper-V switch if it does not exist..."

      trigger.run = {privileged: "true", powershell_elevated_interactive: "true", path: "./scripts/create-nat-hyperv-switch.ps1"}
    end
    # wybor domyslnego switcha
    kiamol.trigger.before :reload do |trigger|
      trigger.info = "Setting Hyper-V switch to 'NATSwitch' to allow for static IP..."

      trigger.run = {privileged: "true", powershell_elevated_interactive: "true", path: "./scripts/set-hyperv-switch.ps1"}
    end  
    # Ustawienie statycznego adresu IP
    kiamol.vm.provision "shell", path: "./scripts/configure-static-ip.sh"

    kiamol.vm.provision :reload
  
  end

end